#!/usr/bin/env ruby
require 'fileutils'
require 'open-uri'

vim_org_scripts = [
  ["jquery",     "12107", "syntax"],
  ["json",       "10853", "syntax"],
  ["railscasts", "8379" , "colors"],
  ["vibrantink", "10117", "colors"]
]

bundles_dir = File.join(File.dirname(__FILE__), "bundle")
FileUtils.cd(bundles_dir)

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.rm_rf name
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

other_scripts = [
  ["Vwilight", "colors", "https://gist.github.com/raw/796172/724c7ca237a7f6b8d857c4ac2991cfe5ffb18087/vwilight.vim"],
  ["bespin",   "colors", "https://raw.github.com/st23am/dotfiles/master/home/.vim/colors/bespin.vim"]
]

other_scripts.each do |name, script_type, url|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.rm_rf name
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open(url).read
  end
end
